apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheusbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheusbeat
  template:
    metadata:
      labels:
        app: prometheusbeat
    spec:
      containers:
      - name: prometheus
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --storage.tsdb.retention.time=48h
        - --web.console.templates=/etc/prometheus/consoles
        - --web.enable-lifecycle
        env:
        - name: NAMESPACE
          value: wp3-components.svc.cluster.local
        image: prom/prometheus
        ports:
        - containerPort: 9090
        resources: {}
        volumeMounts:
        - name: prometheus-config-file
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: config-volume
          mountPath: /etc/prometheus
        - name: prometheus-tsdb
          mountPath: /prometheus
      - name: prometheusbeat
        env:
        - name: LOGSTASHHOST
          value: components.wp3-components.svc.cluster.local:5044
        image: jdtotow/prometheusbeat
        ports:
        - containerPort: 8088
        resources: 
          limits:
            memory: 12Gi
          requests:
            memory: 512Mi
        volumeMounts:
        - mountPath: /config
          name: config-prometheusbeat
      restartPolicy: Always
      volumes:
      - name: prometheus-config-file
        configMap:
          name: configmap-prometheus
          items:
            - key: prometheus.yml
              path: prometheus.yml
      - name: config-volume
        persistentVolumeClaim:
          claimName: config-volume-prometheus
      - name: prometheus-tsdb
        persistentVolumeClaim:
          claimName: prometheus-tsdb-volume
      - name: config-prometheusbeat
        configMap:
          name: configmap-prometheusbeat
          items:
            - key: prometheusbeat.yml
              path: prometheusbeat.yml
